-- $Id: mysql.sql,v 1.1 2003/10/15 02:05:50 kousuke Exp $
CREATE TABLE quiz_icd (
    uid             INT(5) UNSIGNED     NOT NULL DEFAULT 0,
    number_of_times INT(5) UNSIGNED     NOT NULL DEFAULT 0,
    status          TINYINT             NOT NULL DEFAULT 0,
    category        VARCHAR(100) BINARY NOT NULL,
    q0              VARCHAR(100) BINARY NOT NULL,
    q1              VARCHAR(100) BINARY NOT NULL,
    q2              VARCHAR(100) BINARY NOT NULL,
    q3              VARCHAR(100) BINARY NOT NULL,
    q4              VARCHAR(100) BINARY NOT NULL,
    q5              VARCHAR(100) BINARY NOT NULL,
    q6              VARCHAR(100) BINARY NOT NULL,
    q7              VARCHAR(100) BINARY NOT NULL,
    q8              VARCHAR(100) BINARY NOT NULL,
    q9              VARCHAR(100) BINARY NOT NULL,
    c0              TINYINT                      DEFAULT 0,
    c1              TINYINT                      DEFAULT 0,
    c2              TINYINT                      DEFAULT 0,
    c3              TINYINT                      DEFAULT 0,
    c4              TINYINT                      DEFAULT 0,
    c5              TINYINT                      DEFAULT 0,
    c6              TINYINT                      DEFAULT 0,
    c7              TINYINT                      DEFAULT 0,
    c8              TINYINT                      DEFAULT 0,
    c9              TINYINT                      DEFAULT 0,
    correctNum      INT(3) UNSIGNED,
    start_date      DATETIME            NOT NULL,
    quiz_time       BIGINT,
    PRIMARY KEY (uid, number_of_times),
    KEY (uid, number_of_times, status),
    KEY (uid, number_of_times, correctNum, status)
)
    ENGINE = ISAM;
